# Generated by Django 5.0.14 on 2025-12-11 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(help_text='Unique identifier from Firebase', max_length=100, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.FloatField(help_text='Device latitude coordinate')),
                ('longitude', models.FloatField(help_text='Device longitude coordinate')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('polygon_coordinates', models.JSONField(default=list, help_text='List of [latitude, longitude] pairs defining the area boundary')),
                ('center_latitude', models.FloatField(blank=True, null=True)),
                ('center_longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='areas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('nitrogen', 'Nitrogen Analysis'), ('spad', 'SPAD Analysis')], default='nitrogen', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('variogram_model', models.CharField(default='spherical', max_length=50)),
                ('nugget', models.FloatField(blank=True, null=True)),
                ('sill', models.FloatField(blank=True, null=True)),
                ('range_param', models.FloatField(blank=True, null=True)),
                ('low_threshold', models.FloatField(default=1.5, help_text='Below this is LOW')),
                ('high_threshold', models.FloatField(default=2.5, help_text='Above this is HIGH')),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('mean_value', models.FloatField(blank=True, null=True)),
                ('std_value', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_results', to='agriino.area')),
            ],
            options={
                'verbose_name': 'Analysis Result',
                'verbose_name_plural': 'Analysis Results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nitrogen', models.FloatField(help_text='Nitrogen value')),
                ('spad', models.FloatField(blank=True, help_text='SPAD value', null=True)),
                ('a_rgb', models.FloatField(blank=True, null=True)),
                ('a_r', models.FloatField(blank=True, null=True)),
                ('a_g', models.FloatField(blank=True, null=True)),
                ('a_b', models.FloatField(blank=True, null=True)),
                ('r', models.FloatField(blank=True, null=True)),
                ('g', models.FloatField(blank=True, null=True)),
                ('b', models.FloatField(blank=True, null=True)),
                ('o', models.FloatField(blank=True, null=True)),
                ('v', models.FloatField(blank=True, null=True)),
                ('y', models.FloatField(blank=True, null=True)),
                ('t_r', models.FloatField(blank=True, null=True)),
                ('t_g', models.FloatField(blank=True, null=True)),
                ('t_b', models.FloatField(blank=True, null=True)),
                ('eq1', models.FloatField(blank=True, null=True)),
                ('eq2', models.FloatField(blank=True, null=True)),
                ('class_eq1', models.CharField(blank=True, max_length=50, null=True)),
                ('class_eq2', models.CharField(blank=True, max_length=50, null=True)),
                ('firebase_timestamp', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_points', to='agriino.device')),
            ],
            options={
                'verbose_name': 'Device Data',
                'verbose_name_plural': 'Device Data',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KrigingGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('predicted_value', models.FloatField()),
                ('variance', models.FloatField(blank=True, help_text='Kriging variance/uncertainty', null=True)),
                ('classification', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], max_length=10)),
                ('analysis_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grid_points', to='agriino.analysisresult')),
            ],
            options={
                'verbose_name': 'Kriging Grid Point',
                'verbose_name_plural': 'Kriging Grid Points',
                'ordering': ['latitude', 'longitude'],
            },
        ),
        migrations.CreateModel(
            name='AreaDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_devices', to='agriino.area')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_areas', to='agriino.device')),
            ],
            options={
                'ordering': ['-added_at'],
                'unique_together': {('area', 'device')},
            },
        ),
    ]
