# Generated by Django 5.0.14 on 2026-06-25 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriino', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kriginggrid',
            name='classification',
            field=models.CharField(choices=[('deficient', 'Deficient'), ('subnormal', 'Subnormal'), ('normal', 'Normal'), ('high', 'High')], max_length=10),
        ),
    ]
