# Generated by Django 5.0.14 on 2026-07-13 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriino', '0002_alter_kriginggrid_classification'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='devicedata',
            index=models.Index(fields=['device', '-created_at'], name='idx_devicedata_device_date'),
        ),
    ]
