# Agriino Constants Module
from .thresholds import (
    NITROGEN_THRESHOLDS,
    DEFAULT_DEFICIENT_THRESHOLD,
    DEFAULT_SUBNORMAL_THRESHOLD,
    DEFAULT_NORMAL_THRESHOLD,
    DEFAULT_LOW_THRESHOLD,
    DEFAULT_HIGH_THRESHOLD,
    DEFAULT_INFLUENCE_RADIUS_KM,
    DEFAULT_GRID_RESOLUTION,
    DEFAULT_MAX_NEIGHBORS,
    DEFAULT_MIN_NEIGHBORS,
    VARIOGRAM_MODELS,
    CLASSIFICATION_COLORS,
)

__all__ = [
    'NITROGEN_THRESHOLDS',
    'DEFAULT_DEFICIENT_THRESHOLD',
    'DEFAULT_SUBNORMAL_THRESHOLD',
    'DEFAULT_NORMAL_THRESHOLD',
    'DEFAULT_LOW_THRESHOLD',
    'DEFAULT_HIGH_THRESHOLD',
    'DEFAULT_INFLUENCE_RADIUS_KM',
    'DEFAULT_GRID_RESOLUTION',
    'DEFAULT_MAX_NEIGHBORS',
    'DEFAULT_MIN_NEIGHBORS',
    'VARIOGRAM_MODELS',
    'CLASSIFICATION_COLORS',
]
